export * from './auth.controller'
export * from './gym.controller'
export * from './wall.controller'
export * from './color.controller'
export * from './grade.controller'
export * from './event.controller'
export * from './boulder.controller'
